name: 00 - Main CI / CD Pipeline

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
    workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    secrets: inherit #https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit

  sca:
    needs: build
    name: SCA
    uses: ./.github/workflows/sca.yaml
    secrets: inherit
