name: 00 - Main CI / CD Pipeline

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
    workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    secrets: inherit #https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit

  sca:
    needs: build
    name: SCA
    uses: ./.github/workflows/sca.yaml
    secrets: inherit

  sast:
    needs: build
    name: SAST
    uses: ./.github/workflows/sast.yaml
    secrets: inherit

  license-compliance:
    needs: build
    name: License compliance
    uses: ./.github/workflows/license-compliance.yaml
    secrets: inherit

  docker:
    needs: build
    name: Build docker image
    uses: ./.github/workflows/docker.yaml
    secrets: inherit

  container-image-scan:
    needs: docker
    name: Build docker image
    uses: ./.github/workflows/container-image-scan.yaml
    secrets: inherit
    with:
      image-tag: ${{ needs.docker.outputs.image-tag }}
